### ISSUE TITLE
Mailcatcher not working

### ISSUE THREAD

**Issue by mikeaveli007** [SalsaBoy990/docker-wordpress#4]
I'm not sure how the mailcatcher container works exactly but when sending mail from wordpress, I am seeing this error in the wordpress container `/usr/bin/env: 'catchmail': No such file or directory` and I don't see anything in the mailcatcher container's web interface.  Am I missing some config to get them to work together?

**Comment by webandras** [comment]
I set up a new website with this repo, and tested it. For me, it is working with catchmail. The problem is not with mailcatcher.

You can use **mhsendmail** instead, but in this case you need to install it in Dockerfile in the .docker/images/wordpress folder first:

```
RUN curl -O https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
    && chmod +x mhsendmail_linux_amd64 \
    && mv mhsendmail_linux_amd64 /usr/local/bin/mhsendmail
```

And rebuild with docker-compose -f docker-compose.yml up --build again

In addition, you also need to change the **sendmail_path** in php ini to use mhsendmail instead of catchmail:

`sendmail_path = /usr/local/bin/mhsendmail`

This is the file you need to change inside the wordpress container: /usr/local/etc/php/php.ini-development

And finally, you have to restart the wordpress service to apply the changes.
